name: code_with_andrea_flutter
description: Flutter clone of the home page at codewithandrea.com
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false

  assets:
    - assets/
    - assets/fonts/
